version: '3'

services:
  #####################################
  # database
  #####################################
  db:
    build: ${APP_PATH}/docker/mysql56-non-strict
    image: mysql56-non-strict
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fos_webapp


  #####################################
    # redis
  #####################################
  redis:
    image: redis
    ports:
      - "6383:6379"
    expose:
      - "6379"

  #####################################
    # Graciosa app
  #####################################
  app:
    build: ${APP_PATH}/docker/php_base
    ports:
      - "3003:80"
      - "3033:443"
    expose:
      - "3003"
      - "3033"
      - "9000"
    volumes:
      - ${APP_PATH}:/var/www/html
    environment:
      APP_PUBLIC_FOLDER_NAME: ${APP_PUBLIC_FOLDER_NAME}


